Resources:
  SSHSecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: Enable SSH access via port 22 and ICMP traffic
      GroupName: SSH-SG
      SecurityGroupIngress:
      - IpProtocol: TCP
        FromPort: '22'
        ToPort: '22'
        CidrIp: 0.0.0.0/0 
      Tags:
      - Key: "Name"
        Value: "SSH-ICMP"
  EC2Instance:
    Type: 'AWS::EC2::Instance'
    Properties:
      InstanceType: 't2.micro'
      ImageId: 'ami-069aabeee6f53e7bf'
      Tags:
      - Key: "Name"
        Value: "TestEC2_CF"
      SecurityGroups:
        - !Ref SSHSecurityGroup
      KeyName: 'classVM1_kp'