AWSTemplateFormatVersion: 2010-09-09
Description: 'EC2 suites'
Parameters:
  KeyName: 
    Type: AWS::EC2::KeyPair::KeyName
    Description: 'Name of an existing SSH KeyPair to access instance'
  InstanceType:
    Description: 'Allowed types of the instance'
    Type: String
    AllowedValues:
      - t2.micro
      - t3.micro
      - t2.small
      - t2.nano
  EnvType:
    Description: Environment type.
    Default: test
    Type: String
    AllowedValues:
      - prod
      - test
Conditions:
  CreateProdResources: !Equals 
      - !Ref EnvType
      - prod
Resources:
  SSHSecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Condition: CreateProdResources
    Properties:
      GroupDescription: Enable SSH access via port 22 and ICMP traffic
      GroupName: SSH-SG
      SecurityGroupIngress:
      - IpProtocol: TCP
        FromPort: '22'
        ToPort: '22'
        CidrIp: 0.0.0.0/0 
      Tags:
      - Key: "Name"
        Value: "SSH-ICMP"
  EC2Instance:
    Type: 'AWS::EC2::Instance'
    Condition: CreateProdResources
    Properties:
      InstanceType: 't2.micro'
      ImageId: 'ami-069aabeee6f53e7bf'
      AvailabilityZone: us-east-1a
      Tags:
      - Key: "Name"
        Value: "TestEC2_CF"
      SecurityGroups:
        - !Ref SSHSecurityGroup
      KeyName: !Ref KeyName
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      Tags:
        - Key: Name
          Value: ilya-bucket00001
  EBSVolume:
    Type: AWS::EC2::Volume
    Properties:
      Iops: 3000
      Size: 10
      VolumeType: gp3
      AvailabilityZone: !GetAtt EC2Instance.AvailabilityZone
      Tags:
        - Key: Name
          Value: TestVolume
  